# Generated by Django 4.1 on 2022-08-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_info',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('password', models.CharField(max_length=100)),
                ('openstack_user_id', models.CharField(max_length=100, null=True)),
                ('openstack_user_project_id', models.CharField(max_length=100, null=True)),
                ('token', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'accounts_info',
            },
        ),
    ]
