# Generated by Django 4.1 on 2022-08-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='openstack_user_project_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
