# Generated by Django 4.1 on 2022-08-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_info_openstack_user_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
