# Generated by Django 4.1 on 2022-08-31 06:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenstackInstance',
            fields=[
                ('stack_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stack_name', models.CharField(max_length=50, null=True)),
                ('instance_id', models.CharField(max_length=50, null=True)),
                ('instance_name', models.CharField(max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('image_name', models.CharField(max_length=50, null=True)),
                ('flavor_name', models.CharField(max_length=50, null=True)),
                ('ram_size', models.FloatField(validators=[django.core.validators.MaxValueValidator(12)])),
                ('disk_size', models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('num_cpu', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(12)])),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_resource_info', to='account.account_info')),
            ],
        ),
    ]
