# Generated by Django 4.1 on 2022-08-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openstackinstance',
            name='volume_size',
        ),
        migrations.AddField(
            model_name='openstackinstance',
            name='flavor_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='openstackinstance',
            name='instance_image_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='openstackinstance',
            name='instance_ip_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='openstackinstance',
            name='instance_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
