# Generated by Django 4.1 on 2022-08-28 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0005_openstackinstance_instance_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openstackinstance',
            name='disk_size',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='openstackinstance',
            name='ram_size',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
