# Generated by Django 4.1 on 2022-08-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0006_openstackinstance_disk_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openstackinstance',
            name='id',
        ),
        migrations.AlterField(
            model_name='openstackinstance',
            name='stack_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
