# Generated by Django 4.1 on 2022-08-29 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_info_openstack_user_project_id'),
        ('openstack', '0007_remove_openstackinstance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openstackinstance',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_resource_info', to='account.account_info'),
        ),
    ]
