# Generated by Django 4.1 on 2022-08-30 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0008_openstackinstance_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='openstackinstance',
            name='num_cpu',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
